# Generated by Django 4.2.6 on 2023-11-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0004_examsectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionmodel',
            name='examSection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamApp.examsectionmodel'),
        ),
    ]
