# Generated by Django 4.2.6 on 2023-11-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0005_commissionmodel_examsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsectionmodel',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
