# Generated by Django 4.2.6 on 2023-11-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0009_alter_commissionmodel_id_alter_exammodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='credits',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
