# Generated by Django 4.2.6 on 2023-11-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
        ('ExamApp', '0010_remove_subjectmodel_code_remove_subjectmodel_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.tag'),
        ),
    ]
