# Generated by Django 4.2.6 on 2023-11-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
        ('ExamApp', '0011_notesmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blogApp.tag'),
        ),
    ]
