# Generated by Django 4.2.6 on 2023-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0015_image_notesmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
