# Generated by Django 4.2.6 on 2023-12-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0017_blogtitleimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTitleImage',
            new_name='TitleImage',
        ),
    ]
