# Generated by Django 4.2.6 on 2023-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_blogmodel_blogtitleimage'),
        ('ExamApp', '0019_notesmodel_title_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='syllabus',
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='image',
            field=models.ManyToManyField(blank=True, to='ExamApp.image'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogApp.tag'),
        ),
    ]
