# Generated by Django 4.2.6 on 2023-12-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0020_remove_exammodel_syllabus_alter_notesmodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmodel',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
