# Generated by Django 4.2.6 on 2023-12-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_remove_blogmodel_blog_image'),
        ('ExamApp', '0022_examsectionmodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='ExamApp.chaptermodel')),
                ('tags', models.ManyToManyField(blank=True, to='blogApp.tag')),
            ],
        ),
    ]
