# Generated by Django 4.2.6 on 2023-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='subTitle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
