# Generated by Django 4.2.6 on 2023-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blogmodel_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blogImage',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blogImage',
            field=models.ManyToManyField(to='blogApp.blogimage'),
        ),
    ]
