# Generated by Django 4.2.6 on 2023-12-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_blogtitleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blogTitleImage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.blogtitleimage'),
        ),
    ]
