# Generated by Django 4.2.6 on 2023-12-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_blogmodel_blogtitleimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='blogImage',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='blogTitleImage',
            new_name='blog_title_image',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='subTitle',
            new_name='sub_title',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='blogApp.tag'),
        ),
        migrations.AlterField(
            model_name='blogtitleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_title_images/'),
        ),
    ]
