# Generated by Django 4.2.6 on 2023-12-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_rename_blogimage_blogmodel_blog_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_image',
        ),
    ]
