# Generated by Django 4.2.6 on 2023-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_regularuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
