# Generated by Django 4.2.6 on 2023-12-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0006_delete_regularuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='is_regular_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
